package.json
src/App.tsx
src/apollo.ts
src/index.tsx
src/pages/Admin/Home/component.tsx
src/pages/Admin/Home/container.tsx
src/pages/Admin/Home/graphql/getAdminById.ts
src/pages/Admin/Home/index.tsx
src/pages/Loading/index.tsx
src/pages/Loading/styles.module.scss
tslint.json
yarn.lock

Adding Apollo client and conect the front with the back end

---

src/components/Button/styles.module.scss
src/components/CompanyLogo/interface.tsx
src/components/CompanyLogo/styles.module.scss
src/components/ListItem/component.tsx
src/components/ListItem/styles.module.scss
src/components/NavBar/component.tsx
src/components/Tag/styles.module.scss
src/models/RoutesBuilder.ts
src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/index.tsx
src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
src/pages/Applicant/Home/Feed/Offer/component.tsx
src/pages/Applicant/Home/Feed/component.tsx
src/pages/Applicant/Home/Feed/styles.module.scss
src/pages/Applicant/OfferDetail/Detail/component.tsx
src/pages/Applicant/OfferDetail/OfferInfo/styles.module.scss
src/pages/Company/Profile/Detail/component.tsx
src/styles/_variables.scss

Fix offer list styles

---

src/models/hasUniqueValues.ts
src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
src/pages/Applicant/SignUp/container.tsx

Agregado de validaciones en Edit applicant page

---

src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss

Agregado del campo description a la edicion del applican

---

src/pages/Applicant/OfferDetail/Detail/container.tsx

Revert "Disable cache on get offer by uuid"

---

src/pages/LogIn/styles.module.scss

Fix login spacing

---

src/components/CareerSelector/compontent.tsx
src/components/CompanyFields/component.tsx
src/components/EditOffer/index.tsx
src/components/NumberInput/index.tsx
src/components/NumberInput/styles.module.scss
src/components/TextInput/index.tsx
src/components/TextInput/styles.module.scss
src/components/UserInput/index.tsx
src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
src/pages/Public/LogIn/LogInForm/component.tsx

Fix spacing between text fields

---

package.json
src/App.tsx
src/materialUITheme.ts
src/models/hooks/queries/useTranslations.ts
src/pages/Applicant/OfferDetail/container.tsx
src/pages/Public/LogIn/LogInForm/container.tsx
yarn.lock

Se ven como la seccion variants de la documentación:
https://iamhosseindhv.com/notistack/demos#variants

Add toast notifications

---

src/components/TimeHumanizer/index.tsx

Make first letter upercase in TimeHumanizer

---

src/components/ClickableCard/component.tsx
src/components/ClickableCard/styles.module.scss
src/components/Window/component.tsx
src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/container.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/index.ts
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/interfaces.ts
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/index.ts
src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/interfaces.ts
src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/ListInfo/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/component.tsx
src/pages/Admin/Home/Dashboard/TaskList/container.tsx
src/pages/Admin/Home/Dashboard/TaskList/interface.ts
src/pages/Admin/Home/Dashboard/TaskList/styles.module.scss
src/pages/Admin/Home/Dashboard/component.tsx
src/pages/Admin/Home/Dashboard/styles.module.scss
src/styles/_variables.scss

Fix scrolling in admin dashboard

---

src/graphql/queries/getCurrentUser.graphql
src/models/CurrentApplicant.ts
src/models/CurrentApprovable.ts
src/models/CurrentCompany.ts
src/models/CurrentUser.ts
src/models/Errors/PendingApplicantError.ts
src/models/Errors/RejectedApplicantError.ts
src/models/Errors/index.ts
src/models/NavBarLinks/ApplicantNavBarLinks.ts
src/models/NavBarLinks/CompanyNavBarLinks.ts
src/models/NavBarLinks/getTooltipMessage.ts
src/models/Permissions/ApplicantPermissions.ts
src/models/Permissions/Permissions.ts
src/models/Router/ApplicantRouter.ts
src/models/Router/Router.ts
src/models/hooks/queries/useCurrentUser.ts
src/test/models/CurrentUser.test.ts
src/test/models/NavBarLinks/NavBarLinks.test.ts
src/test/models/Permissions/Permissions.test.ts
src/test/models/Router/Router.test.ts

Add frontend permissions for applicant

---

src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/Actions/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/Actions/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/MainTitle/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/MainTitle/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/ListInfo/styles.module.scss
src/pages/Applicant/Companies/styles.module.scss
src/styles/_variables.scss
src/styles/mixins/_overflowYOverlay.scss

Fix admin task detail styles fix

---

src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss

Expand detail content 

---

src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss

Fix mobile layout of offer feed

---

src/pages/Admin/Home/Dashboard/TaskList/ListInfo/component.tsx
src/pages/Admin/Home/Dashboard/TaskList/ListInfo/container.tsx
src/pages/Admin/Home/Dashboard/TaskList/ListInfo/index.ts
src/pages/Admin/Home/Dashboard/TaskList/component.tsx
src/pages/Admin/Home/Dashboard/TaskList/container.tsx
src/pages/Admin/Home/Dashboard/TaskList/interface.ts
src/pages/Admin/Home/Dashboard/component.tsx

Fix Task List mejor comunicación

---

src/components/OfferInfo/component.tsx
src/components/OfferInfo/styles.module.scss
src/components/OfferTargetApplicantType/component.tsx
src/components/OfferTargetApplicantType/container.tsx
src/components/OfferTargetApplicantType/index.ts
src/components/OfferTargetApplicantType/interfaces.ts
src/components/OfferWorkload/component.tsx
src/graphql/queries/getOfferByUuid.graphql

Add OfferTargetApplicantType component

---

src/components/CareersDetail/styles.module.scss
src/materialUITheme.ts
src/styles/_variables.scss

Copiando los valores usados en google.com (con ajustes menores)
Primero screen nuevo, después el viejo:

Make fonts and spacing a little smaller

---

src/components/CompanyDetail/index.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailContent/container.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/container.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/container.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/interfaces.ts
src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDetailContent/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss

Fix admin job application styles

---

src/ApolloClient.ts
src/components/MainContent/component.tsx
src/components/Window/DesktopOnlyOverlay/component.tsx
src/components/Window/DesktopOnlyOverlay/container.tsx
src/components/Window/DesktopOnlyOverlay/index.ts
src/components/Window/DesktopOnlyOverlay/interface.ts
src/components/Window/DesktopOnlyOverlay/styles.module.scss
src/components/Window/component.tsx
src/components/Window/styles.module.scss
src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/UserDetails/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskList/styles.module.scss
src/pages/Admin/Home/Dashboard/component.tsx
src/styles/_variables.scss
src/styles/base.scss

(Screens tomadas antes del cambio en los títulos en las translations)
https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/

Improve admin responsiveness

---

src/components/Button/styles.module.scss
src/components/CareerSelector/component.tsx
src/components/CareerSelector/interface.ts
src/components/NumberInput/index.tsx
src/components/NumberInput/interfaces.ts
src/pages/Public/Register/styles.module.scss

Shorten career selector label

---

src/pages/Admin/Applicants/ApplicantList/ListContainer/styles.module.scss
src/pages/Admin/Applicants/ApplicantList/ListContent/Row/styles.module.scss
src/pages/Admin/Applicants/ApplicantList/ListHeader/HeaderContainer/styles.module.scss
src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
src/styles/mixins/_scrollOverlay.scss

Fix admin list styles

---

src/models/NavBarLinks/AdminNavBarLinks.ts
src/models/RoutesBuilder.ts
src/pages/Admin/Companies/container.tsx
src/pages/Admin/Companies/index.ts
src/pages/Admin/routes.tsx
src/test/models/NavBarLinks/NavBarLinks.test.ts

Add Empresas link in navbar

---

src/components/CompanyFields/component.tsx
src/components/CompanyFields/interface.ts
src/models/hooks/mutations/useCreateCompany.ts
src/pages/Company/SignUp/component.tsx

agregado de businessName en el registro de company (razon social)

---

src/graphql/queries/getMyCareers.graphql
src/graphql/queries/index.ts
src/models/OfferFilter.ts
src/models/hooks/queries/index.ts
src/models/hooks/queries/useApprovedOffers.ts
src/models/hooks/queries/useMyCareers.ts
src/models/hooks/queries/usePaginatedQuery.ts
src/pages/Applicant/Home/Feed/container.tsx
src/test/models/OfferFilter.test.ts

al entrar:
al remover los 2 filtros:

Select current applicant's careers by default in homepage

---

src/components/Label/index.tsx
src/components/Label/styles.module.scss
src/components/SharedStatusLabel/component.tsx
src/components/StatusTitle/index.tsx
src/pages/Admin/Applicants/ListContentItem/index.tsx
src/pages/Admin/Companies/ListContentItem/index.tsx
src/pages/Admin/Home/Dashboard/TaskList/AdminTask/StatusIcon/styles.module.scss

Parametrize label dimensions

---

src/pages/Admin/Companies/container.tsx

pagination del listado de companies
